name: Docker Image CI

on:
#   schedule:
#     - cron: '0 0 1 * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY_DH: docker.io
  REGISTRY_GH: ghcr.io
  IMAGE_NAME: lamusmaser/word-phrase-frequency-analyzer

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Install/Config Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: latest

    - name: Log into registry (Docker)
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_DH }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Log into registry (GitHub)
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_GH }}
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_PAT }}

    - name: Build and push Docker image - build tag
      id: build-and-push
      uses: docker/build-push-action@v5
      with:
          context: .
          push: true
          tags: lamusmaser/word-phrase-frequency-analyzer:build
          platforms: linux/arm64/v8
          secrets: GIT_AUTH_TOKEN=${{ secrets.GH_PAT }}
 
  build-and-push-main:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'

    steps:
    - uses: actions/checkout@v4
    - name: Generate datetag
      id: meta
      run: |
        echo "datetag=$(date +%y.%m.%d)" >> $GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Install/Config Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into registry (Docker)
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_DH }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Log into registry (GitHub)
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_GH }}
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_PAT }}

    - name: Build and push Docker image - latest tag
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      id: build-and-push
      uses: docker/build-push-action@v5
      with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
          tags: lamusmaser/word-phrase-frequency-analyzer:${{ steps.meta.outputs.datetag }}, lamusmaser/word-phrase-frequency-analyzer:latest
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          secrets: GIT_AUTH_TOKEN=${{ secrets.GH_PAT }}